# Generated by Django 4.2.6 on 2023-10-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofileabout_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileabout',
            name='birthday',
            field=models.DateField(blank=True, default='2023-06-10', null=True),
        ),
    ]
