# Generated by Django 4.2.6 on 2023-10-16 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('exterior_color', models.CharField(max_length=50)),
                ('interior_color', models.CharField(max_length=50)),
                ('door', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=15)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('vehicle_type', models.CharField(max_length=50)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default='Automatic', max_length=50)),
                ('passenger_capacity', models.PositiveSmallIntegerField()),
                ('luggage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fuel_type', models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=50)),
                ('registration_number', models.CharField(max_length=50)),
                ('car_picture_main', models.ImageField(upload_to='vehicles/')),
                ('other_car_picture_one', models.ImageField(upload_to='vehicles/')),
                ('other_car_picture_two', models.ImageField(upload_to='vehicles/')),
                ('other_car_picture_three', models.ImageField(upload_to='vehicles/')),
                ('other_car_picture_four', models.ImageField(upload_to='vehicles/')),
            ],
        ),
    ]
